version: "3.3"
services:
  postgres:
    image: postgres:14
    ports:
      - "2432:5432"
    environment:
      POSTGRES_USER: nerves_hub
      POSTGRES_PASSWORD: nerves_hub
      POSTGRES_DB: nerves_hub
      PGDATA: /data
    volumes:
      - ~/db/nerveshub/postgres:/data
